version: '3.4'

services:
  buyrequest_api:
    image: buyrequestapi:dev
    container_name: BuyRequest_Api
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "BuyRequest_Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_buyrequest_api$
    volumes:
      - C:\Users\rcm_r\source\repos\FinancialAPP\BuyRequest_Api:/app
      - C:\Users\rcm_r\source\repos\FinancialAPP:/src
      - C:\Users\rcm_r\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_buyrequest_api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_buyrequest_api$ \"/app/bin/Debug/net5.0/BuyRequest_Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  cashbook_api:
    image: cashbookapi:dev
    container_name: CashBook_Api
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "CashBook_Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_cashbook_api$
    volumes:
      - C:\Users\rcm_r\source\repos\FinancialAPP\CashBook_Api:/app
      - C:\Users\rcm_r\source\repos\FinancialAPP:/src
      - C:\Users\rcm_r\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_cashbook_api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_cashbook_api$ \"/app/bin/Debug/net5.0/CashBook_Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  document_api:
    image: documentapi:dev
    container_name: Document_Api
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Document_Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_document_api$
    volumes:
      - C:\Users\rcm_r\source\repos\FinancialAPP\Document_Api:/app
      - C:\Users\rcm_r\source\repos\FinancialAPP:/src
      - C:\Users\rcm_r\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_document_api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_document_api$ \"/app/bin/Debug/net5.0/Document_Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  productapi:
    image: productapi:dev
    container_name: ProductAPI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ProductAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_productapi$
    volumes:
      - C:\Users\rcm_r\source\repos\FinancialAPP\ProductAPI:/app
      - C:\Users\rcm_r\source\repos\FinancialAPP:/src
      - C:\Users\rcm_r\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_productapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_productapi$ \"/app/bin/Debug/net5.0/ProductAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
